<h3>📂 Advanced-np.ipynb

In [1]:
import numpy as np

Day-1
1) Generate a 5×5 identity matrix.
2) Create a diagonal matrix with values [2, 4, 6, 8].
3) Create a 3×3 random matrix and find its transpose.

In [ ]:
#que 1
id_matrix = np.identity(n=5)
print("The identity matrix is ")
print(id_matrix)

The identity matrix is 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
#que 2
dio = np.zeros(shape = (4,4))
np.fill_diagonal(dio , val = [2,4,6,8])
print("The matrix is:")
print(dio)


The matrix is:
[[2. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


In [19]:
matrix = np.random.randint(0,69 , size = (3,3))
transpose_matrix = np.transpose(matrix)
print("The orignal matrix is:")
print(matrix)
print("The Transpose matrix is :")
print(transpose_matrix)

The orignal matrix is:
[[13 51  0]
 [59 58 11]
 [48 53 17]]
The Transpose matrix is :
[[13 59 48]
 [51 58 53]
 [ 0 11 17]]
