<h3>📂 Advanced-np.ipynb

In [2]:
import numpy as np

Day-1
1) Generate a 5×5 identity matrix.
2) Create a diagonal matrix with values [2, 4, 6, 8].
3) Create a 3×3 random matrix and find its transpose.

In [3]:
#que 1
id_matrix = np.identity(n=5)
print("The identity matrix is ")
print(id_matrix)

The identity matrix is 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
#que 2
dio = np.zeros(shape = (4,4))
np.fill_diagonal(dio , val = [2,4,6,8])
print("The matrix is:")
print(dio)


The matrix is:
[[2. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


In [5]:
matrix = np.random.randint(0,69 , size = (3,3))
transpose_matrix = np.transpose(matrix)
print("The orignal matrix is:")
print(matrix)
print("The Transpose matrix is :")
print(transpose_matrix)

The orignal matrix is:
[[ 3 61 19]
 [ 7 38 50]
 [ 2 61 16]]
The Transpose matrix is :
[[ 3  7  2]
 [61 38 61]
 [19 50 16]]


<h5>Day -2

1) Create two random 2×2 matrices and perform matrix multiplication (np.matmul).
2) Create a 3×3 random matrix and find its determinant.
3) Create a 4×4 random matrix and find its inverse (if possible).

In [ ]:
#que 1
matrix_1 , matrix_2 = np.matrix([[1,2],[3,4]]) , np.matrix([[5,6],[7,8]])
multi = np.matmul(matrix_1 , matrix_2)
print("The Matrix multiplication : \n" ,multi)

The Matrix multiplication : 
 [[19 22]
 [43 50]]


In [30]:
#que 2 
matrix = np.random.randint(1,50 , size = (3,3))
determiant = np.linalg.det(matrix)
print("The determiant of matrix :" ,determiant )

The determiant of matrix : 9941.99999999999


In [34]:
#que 3
matrix = np.random.randint(1,50 , size = (4,4))
inverse = np.linalg.inv(matrix)
print("The orginal matrix is : \n" , matrix)
print("The inversed matirx is : \n" , inverse)

The orginal matrix is : 
 [[23 28 41 17]
 [47 30  7 30]
 [34 33 46  6]
 [10  2 35 25]]
The inversed matirx is : 
 [[-0.0881111   0.01791085  0.05697848  0.02474769]
 [ 0.09807399 -0.00265634 -0.04733629 -0.052142  ]
 [-0.01077275 -0.01275529  0.01965043  0.01791571]
 [ 0.04248037  0.01090557 -0.04651509  0.00919029]]
