<h3>📂 Advanced-np.ipynb

In [3]:
import numpy as np

Day-1
1) Generate a 5×5 identity matrix.
2) Create a diagonal matrix with values [2, 4, 6, 8].
3) Create a 3×3 random matrix and find its transpose.

In [4]:
#que 1
id_matrix = np.identity(n=5)
print("The identity matrix is ")
print(id_matrix)

The identity matrix is 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
#que 2
dio = np.zeros(shape = (4,4))
np.fill_diagonal(dio , val = [2,4,6,8])
print("The matrix is:")
print(dio)


The matrix is:
[[2. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


In [6]:
matrix = np.random.randint(0,69 , size = (3,3))
transpose_matrix = np.transpose(matrix)
print("The orignal matrix is:")
print(matrix)
print("The Transpose matrix is :")
print(transpose_matrix)

The orignal matrix is:
[[67 32 54]
 [33 25 37]
 [50 59 13]]
The Transpose matrix is :
[[67 33 50]
 [32 25 59]
 [54 37 13]]


<h5>Day -2

1) Create two random 2×2 matrices and perform matrix multiplication (np.matmul).
2) Create a 3×3 random matrix and find its determinant.
3) Create a 4×4 random matrix and find its inverse (if possible).

In [7]:
#que 1
matrix_1 , matrix_2 = np.matrix([[1,2],[3,4]]) , np.matrix([[5,6],[7,8]])
multi = np.matmul(matrix_1 , matrix_2)
print("The Matrix multiplication : \n" ,multi)

The Matrix multiplication : 
 [[19 22]
 [43 50]]


In [8]:
#que 2 
matrix = np.random.randint(1,50 , size = (3,3))
determiant = np.linalg.det(matrix)
print("The determiant of matrix :" ,determiant )

The determiant of matrix : -6149.999999999994


In [9]:
#que 3
matrix = np.random.randint(1,50 , size = (4,4))
inverse = np.linalg.inv(matrix)
print("The orginal matrix is : \n" , matrix)
print("The inversed matirx is : \n" , inverse)

The orginal matrix is : 
 [[16 21 10 24]
 [ 8 42 43 37]
 [ 4 12 46 22]
 [17 21  9 19]]
The inversed matirx is : 
 [[-0.06912328 -0.04179547  0.02726598  0.13713367]
 [-0.09665719  0.04233131 -0.0340258   0.07905692]
 [-0.06392976 -0.00377149  0.02834797  0.0552739 ]
 [ 0.1989613  -0.0076048  -0.0002164  -0.18362805]]


<h5>Day 3

1) Create two arrays: a= np.array([1,2,3]), b = np.array([10,20,30])
    3) Use broadcasting to add them to a 3×3 matrix.
2) Stack two 1D arrays [1,2,3] and [4,5,6] vertically and horizontally.
3) Create a 4×4 random matrix and find its eigenvalues and eigenvectors.

In [ ]:
a  , b= np.array([1,2,3]) , np.array([10,20,30])
matrix = a.reshape(3,1) +b
print(matrix)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [18]:
h_stack = np.hstack((a,b))
v_stack = np.vstack((a,b))
print(f"The horizontally stacked array is {h_stack} and vertical stacked array is {v_stack}")

The horizontally stacked array is [ 1  2  3 10 20 30] and vertical stacked array is [[ 1  2  3]
 [10 20 30]]


In [43]:
M = np.random.rand(4, 4) 
eigvals, eigvecs = np.linalg.eig(M)

print("Matrix:\n", M)
print("\nEigenvalues:\n", eigvals)
print("\nEigenvectors:\n", eigvecs)


Matrix:
 [[0.70563767 0.61291196 0.38203216 0.2268938 ]
 [0.64358794 0.09978646 0.16013547 0.18723536]
 [0.73455079 0.16334866 0.68645713 0.96235749]
 [0.70244935 0.30618641 0.8907396  0.20652611]]

Eigenvalues:
 [ 1.98640164  0.52074805 -0.28587628 -0.52286604]

Eigenvectors:
 [[ 0.42098074  0.52406792 -0.55442631  0.19180119]
 [ 0.25540227  0.38998783  0.78569556 -0.24413011]
 [ 0.67591687 -0.67104378  0.01571143 -0.64165043]
 [ 0.54834412 -0.35066018  0.27394728  0.70135406]]
