Array-Creation 
Day - 1
1) Create a 1D array of numbers from 1 to 20.
2) Create a 2D array of shape 4×5 with all zeros.
3) Create a 3D array of shape 2×3×4 filled with random integers (1–50).

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,21)
print("The que 1 array is :", arr)

The que 1 array is : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
arr = np.zeros(shape=(4,5))
print("A Array with only zero elements")
print(arr)

A Array with only zero elements
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
arr = np.random.randint(1,51 , size = (2,3,4))
print(arr)

[[[45 33  1 44]
  [26 26 44 24]
  [18 37 13 40]]

 [[44 47 12 38]
  [26  1 39 24]
  [48 22 14 19]]]
