Array-Properties-&-Reshaping
Day-1

1) Create an array of numbers 1–12. Print: shape, size, ndim, dtype.
2) Reshape it into a 3×4 matrix.
3) Flatten the matrix back into 1D.

In [2]:
import numpy as np

In [3]:
#que 1
arr = np.arange(1,13)
print("The shape of array is:" , arr.shape)
print("the size of array is:" , arr.size)
print("The dimensions of the array is :" , arr.ndim)
print("The data type od array is :" , type(arr))

The shape of array is: (12,)
the size of array is: 12
The dimensions of the array is : 1
The data type od array is : <class 'numpy.ndarray'>


In [4]:
#que 2
arr = arr.reshape(3,4)
print("The reshaped array is :")
print(arr)

The reshaped array is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
#que 3
arr = arr.reshape(-1) # use flatten() or ravel
print("The flatten matrix is :" ,arr)

The flatten matrix is : [ 1  2  3  4  5  6  7  8  9 10 11 12]


<h5>Day-2

1) Create an array of numbers 1–24. Reshape into 2×3×4. Print shape & ndim.
2) Reshape the same array into 6×4, then into 12×2.
3) Take a random 3×3 matrix and compute its transpose.

In [ ]:
#que 1
arr = np.arange(1,25)
arr = arr.reshape(2,3,4)
print(f"{arr} \nThe shape of arr after reshaping is {arr.shape} , and the dimension is {arr.ndim}")

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 
The shape of arr after reshaping is (2, 3, 4) , and the dimension is 3


In [ ]:
#que 2
arr = arr.reshape(6,4) 
print(arr.shape)
arr = arr.reshape(12,2) 
print(arr.shape)

(6, 4)
(12, 2)


In [ ]:
#que 3
matrix = np.random.rand(3,3)
traspose = np.transpose(matrix)
print("The orignal matrix is: \n",matrix)
print("The transpose matrix is\n" , traspose)

The orignal matrix is: 
 [[0.14457103 0.281387   0.53347147]
 [0.55264378 0.75933369 0.05759749]
 [0.80572074 0.18131343 0.11339681]]
The transpose matrix is
 [[0.14457103 0.55264378 0.80572074]
 [0.281387   0.75933369 0.18131343]
 [0.53347147 0.05759749 0.11339681]]
