Array-Properties-&-Reshaping
Day-1

1) Create an array of numbers 1–12. Print: shape, size, ndim, dtype.
2) Reshape it into a 3×4 matrix.
3) Flatten the matrix back into 1D.

In [1]:
import numpy as np

In [ ]:
#que 1
arr = np.arange(1,13)
print("The shape of array is:" , arr.shape)
print("the size of array is:" , arr.size)
print("The dimensions of the array is :" , arr.ndim)
print("The data type od array is :" , type(arr))

The shape of array is: (12,)
the size of array is: 12
The dimensions of the array is : 1
The data type od array is : <class 'numpy.ndarray'>


In [8]:
#que 2
arr = arr.reshape(3,4)
print("The reshaped array is :")
print(arr)

The reshaped array is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#que 3
arr = arr.reshape(-1) # use flatten() or ravel
print("The flatten matrix is :" ,arr)

The flatten matrix is : [ 1  2  3  4  5  6  7  8  9 10 11 12]
