Array-Properties-&-Reshaping
Day-1

1) Create an array of numbers 1–12. Print: shape, size, ndim, dtype.
2) Reshape it into a 3×4 matrix.
3) Flatten the matrix back into 1D.

In [1]:
import numpy as np

In [2]:
#que 1
arr = np.arange(1,13)
print("The shape of array is:" , arr.shape)
print("the size of array is:" , arr.size)
print("The dimensions of the array is :" , arr.ndim)
print("The data type od array is :" , type(arr))

The shape of array is: (12,)
the size of array is: 12
The dimensions of the array is : 1
The data type od array is : <class 'numpy.ndarray'>


In [3]:
#que 2
arr = arr.reshape(3,4)
print("The reshaped array is :")
print(arr)

The reshaped array is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
#que 3
arr = arr.reshape(-1) # use flatten() or ravel
print("The flatten matrix is :" ,arr)

The flatten matrix is : [ 1  2  3  4  5  6  7  8  9 10 11 12]


<h5>Day-2

1) Create an array of numbers 1–24. Reshape into 2×3×4. Print shape & ndim.
2) Reshape the same array into 6×4, then into 12×2.
3) Take a random 3×3 matrix and compute its transpose.

In [5]:
#que 1
arr = np.arange(1,25)
arr = arr.reshape(2,3,4)
print(f"{arr} \nThe shape of arr after reshaping is {arr.shape} , and the dimension is {arr.ndim}")

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 
The shape of arr after reshaping is (2, 3, 4) , and the dimension is 3


In [6]:
#que 2
arr = arr.reshape(6,4) 
print(arr.shape)
arr = arr.reshape(12,2) 
print(arr.shape)

(6, 4)
(12, 2)


In [7]:
#que 3
matrix = np.random.rand(3,3)
traspose = np.transpose(matrix)
print("The orignal matrix is: \n",matrix)
print("The transpose matrix is\n" , traspose)

The orignal matrix is: 
 [[0.57049009 0.71469569 0.53408663]
 [0.05369509 0.76822011 0.17225772]
 [0.29009528 0.38702487 0.67146844]]
The transpose matrix is
 [[0.57049009 0.05369509 0.29009528]
 [0.71469569 0.76822011 0.38702487]
 [0.53408663 0.17225772 0.67146844]]


<h5>Day 2

1) Create a 1D array of 36 numbers. Reshape it into:
    1) 6×6
    2) 3×3×4
    3) Verify that all reshaped arrays contain the same data.
2) Take a 2D random array and compute both row-wise mean and column-wise mean.
3) Flatten a 3D array into 1D and then reshape back into 3D again.

In [ ]:
#que 1
arr = np.arange(1 ,37)
arr_6x6 = arr.reshape(6,6)
arr_3x3x4 = arr.reshape(3,3,4)
print("Reshape into 6x6 :\n" , arr_6x6)
print("Reshape into 3x3x4 : \n" , arr_3x3x4)
print("Checking the 6x6" : , np.array_equal(arr , np.ravel(arr_6x6)))
print("Checking the 3x3x4" : , np.array_equal(arr , np.ravel(arr_3x3x4)))


Reshape into 6x6 :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Reshape into 3x3x4 : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
Checking the 6x6 True
Checking the 3x3x4 True


In [ ]:
#Que 2
arr = np.random.randint(1,51 , size = (2,10))
print(f"The array is {arr[0]}. mean is {arr[0,].mean()}, median is {np.median(arr[0])}.")
print(f"The array is {arr[1]}. mean is {arr[1,].mean()}, median is {np.median(arr[1])}.")
print(f"The array is  {arr[0:,0]}. mean is {arr[0:,0].mean()}")
arr

The array is [ 9 34 42 43 42 47 27 49 37  1]. mean is 33.1, median is 39.5.
The array is [31 11  5 46 39 20 29  4 14 10]. mean is 20.9, median is 17.0.
The array is  [ 9 31]. mean is 20.0


array([[ 9, 34, 42, 43, 42, 47, 27, 49, 37,  1],
       [31, 11,  5, 46, 39, 20, 29,  4, 14, 10]], dtype=int32)

In [47]:
#que 3
arr = np.arange(1,10).reshape(3,3)
print("The orginal array is : \n" , arr)
arr_to_1d = arr.flatten()
print(f"The flated array into 1d is {arr_to_1d} and the dimension of it is {arr_to_1d.ndim } and the shape is {arr_to_1d.shape}")
arr_to_3d = arr.reshape(3,3)
print(f"The flated array into 3d is \n{arr_to_3d}\n and the dimension of it is {arr_to_3d.ndim } and the shape is {arr_to_3d.shape}")


The orginal array is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The flated array into 1d is [1 2 3 4 5 6 7 8 9] and the dimension of it is 1 and the shape is (9,)
The flated array into 3d is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 and the dimension of it is 2 and the shape is (3, 3)
