Array-Creation 
Day - 1
1) Create a 1D array of numbers from 1 to 20.
2) Create a 2D array of shape 4×5 with all zeros.
3) Create a 3D array of shape 2×3×4 filled with random integers (1–50).

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,21)
print("The que 1 array is :", arr)

The que 1 array is : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
arr = np.zeros(shape=(4,5))
print("A Array with only zero elements")
print(arr)

A Array with only zero elements
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
arr = np.random.randint(1,51 , size = (2,3,4))
print(arr)

[[[45 33  1 44]
  [26 26 44 24]
  [18 37 13 40]]

 [[44 47 12 38]
  [26  1 39 24]
  [48 22 14 19]]]


<h5>Day-2<h5>

1) Create an array of even numbers between 2 and 40.
2) Create a 4×4 array filled with random floats (0–1).
3) Create a 3×3 array with all elements = 7.

In [ ]:
#que 1
arr = np.arange(2,42 , step=2)
print("Even array from 2 to 40 :" ,arr)

Even array from 2 to 40 : [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
#que 2
matrix = np.random.rand(4,4) #np.random.uniform(0.0 , 1.0 , size = (4,4))
print("Matrix with random floats(0-1)")
print(matrix)

Matrix with random floats(0-1)
[[0.03459825 0.88692439 0.29577854 0.08316901]
 [0.6671978  0.56062654 0.8031926  0.78596131]
 [0.86025324 0.54676116 0.79020529 0.65443363]
 [0.83822791 0.85694698 0.63530414 0.16634589]]


In [28]:
#que 3 
matrix = np.full((3,3) , 7)
print("Matirx with only element 7")
print(matrix)

Matirx with only element 7
[[7 7 7]
 [7 7 7]
 [7 7 7]]
