Array-Creation 
Day - 1
1) Create a 1D array of numbers from 1 to 20.
2) Create a 2D array of shape 4×5 with all zeros.
3) Create a 3D array of shape 2×3×4 filled with random integers (1–50).

In [26]:
import numpy as np

In [27]:
arr = np.arange(1,21)
print("The que 1 array is :", arr)

The que 1 array is : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
arr = np.zeros(shape=(4,5))
print("A Array with only zero elements")
print(arr)

A Array with only zero elements
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
arr = np.random.randint(1,51 , size = (2,3,4))
print(arr)

[[[11 24 36 40]
  [24  3 22  2]
  [24 44 30 38]]

 [[ 2 21 33 12]
  [22 44 25 49]
  [27 42 28 16]]]


<h5>Day-2<h5>

1) Create an array of even numbers between 2 and 40.
2) Create a 4×4 array filled with random floats (0–1).
3) Create a 3×3 array with all elements = 7.

In [30]:
#que 1
arr = np.arange(2,42 , step=2)
print("Even array from 2 to 40 :" ,arr)

Even array from 2 to 40 : [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [31]:
#que 2
matrix = np.random.rand(4,4) #np.random.uniform(0.0 , 1.0 , size = (4,4))
print("Matrix with random floats(0-1)")
print(matrix)

Matrix with random floats(0-1)
[[0.23277134 0.09060643 0.61838601 0.38246199]
 [0.98323089 0.46676289 0.85994041 0.68030754]
 [0.45049925 0.01326496 0.94220176 0.56328822]
 [0.3854165  0.01596625 0.23089383 0.24102547]]


In [32]:
#que 3 
matrix = np.full((3,3) , 7)
print("Matirx with only element 7")
print(matrix)

Matirx with only element 7
[[7 7 7]
 [7 7 7]
 [7 7 7]]


<h5>Day 3

1) Create an array of shape 5×5 with values from 0–24 using np.arange.
2) Create a logarithmically spaced array of 10 values between 10^1 and 10^3.
3) Generate a 3×3 random integer matrix between 1–100 with a fixed seed (np.random.seed(42)) so results are reproducible.

In [33]:
arr = np.arange(0,25).reshape(5,5)
print("The array is :\n " , arr)

The array is :
  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [34]:
#que 2 
arr = np.logspace(1,3 , num= 10)
print("The logarithmically spaced array is : ", arr)

The logarithmically spaced array is :  [  10.           16.68100537   27.82559402   46.41588834   77.42636827
  129.1549665   215.443469    359.38136638  599.48425032 1000.        ]


In [35]:
#que 3
np.random.seed(42)
arr = np.random.randint(1 , 100 , size = (3,3))
print("Thee array is :\n " , arr)

Thee array is :
  [[52 93 15]
 [72 61 21]
 [83 87 75]]
