<h3>Indexing-&-Slicing


Day-1
1) From the array [10, 20, 30, 40, 50, 60], extract every 2nd element.
2) From a 3×3 matrix of numbers 1–9, extract the 2nd row.
3) From the same matrix, extract the last column.

In [10]:
import numpy as np

In [18]:
arr = np.array([10,20,30,40,50,60])
print(arr)
print("Every 2 element from the arr is :" , arr[::2]) #step is 2 so it skips 2 element.

[10 20 30 40 50 60]
Every 2 element from the arr is : [10 30 50]


In [25]:
matrix = np.arange(1,10).reshape(3,3)
print("The second row is",matrix[1])

The second row is [4 5 6]


In [67]:
matrix = np.arange(1,17).reshape(4,4)
print("The last row of matrix is :",matrix[: , -1]) # all rows , last column

The last row of matrix is : [ 4  8 12 16]


<h5>Day-2<h5>

1) From the array [5, 10, 15, 20, 25, 30, 35, 40], extract elements at indices [1, 3, 5] using fancy indexing.
2) From a 4×4 matrix (values 1–16), slice out the 2×2 submatrix from the bottom-right corner.
3) From the same matrix, select all elements greater than 10 (boolean indexing).

In [11]:
arr = np.array([5,10,15,20,25,30,35,40])
indexed = arr[[1,3,5]]
print(indexed)

[10 20 30]


In [17]:
arr = np.arange(1,17).reshape(4,4)
submatrix = arr[2:4 , 2:4]
print("The full matrix is \n" , arr)
print("The submatrix is \n" , submatrix)

The full matrix is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The submatrix is 
 [[11 12]
 [15 16]]


In [18]:
grater_10 = arr[arr > 10]
print("Values greater then 10 in the matrix: " , grater_10)

Values greater then 10 in the matrix:  [11 12 13 14 15 16]
